# Generated by Django 3.0.1 on 2020-01-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ISBN',
        ),
    ]
