# Generated by Django 3.0.1 on 2020-01-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodels', '0003_remove_book_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
